### ISSUE TITLE
bug with new stringr release? wildcard does not match \n

### ISSUE THREAD

**Issue by Tabbob** [hadley/stringr#69]
The R-package stringr behaves differently between R-Version 3.1.1 and 3.2.0 (verified on two different machines). Under 3.2.0 the wildcard does not match \n

simplified example:
x <- "abc\n23"

in version R-3.1.1
str_extract_all(x, "a.+?[[:digit:]]{2}")
[1] "abc\n23"

in version R-3.2.0
str_extract_all(x, "a.+?[[:digit:]]{2}")
[[1]]
character(0)

**Comment by gagolews** [comment]
@Tabbob it's not a bug, it's a feature.

the same happens while PCRE is in use:

```
> grepl(".", "\n", perl=TRUE)
[1] FALSE
> grepl(".", "\n", perl=FALSE)
[1] TRUE
```

check this out:

```
> stringr::str_extract_all("abc\n23", stringr::regex("a.+?[[:digit:]]{2}", dotall=TRUE))
[[1]]
[1] "abc\n23"
```

**Comment by Tabbob** [comment]
Many thanks! I thought it was a bug - now I know it's a feature.

**Comment by petermeissner** [comment]
While this gives more control it also changes the default and expected behavior of stringr functions - meaning that **code breaks unexpectedly**. 

Furthermore, it does somehow counter the purpose of stringr functions as *less-options-getting-more-work-done* functions. As common it might be in other languages it does make any statement about how useful this is in real life.

Maybe choosing `dotall=TRUE` as the default would be - especially since it is stringr's old and expected behavior and stringi still is young and evolving. 

I see me re-writing things like that ...

```
str_extract("4553-kjhd\ng\nafk\njasgd\nkjgaf", "-.*")
```

... as ...

```
str_extract("4553-kjhd\ng\nafk\njasgd\nkjgaf",  regex("-.*", dotall=TRUE))
```

... or as ... 

```
str_extract("4553-kjhd\ng\nafk\njasgd\nkjgaf",  "-[\\s\\S]*")
```

**Comment by petermeissner** [comment]
> gagolews in https://github.com/Rexamine/stringi/issues/181 : 
> Yes, it will persist as it is default in ICU. If you want different behavior in stringr (e.g, if stringr=0.6 had something like dotall=TRUE both for TRE and PERL /I'm unsure/), ask @hadley

> Nope, perl also has dotall=FALSE in base R

Yes, this should be handled by stringr.

**Comment by hadley** [comment]
I have regular expressions that include `(.|\n)+` which suggests `dotall = TRUE` is not the default, at least in my head. I'd prefer to stay as consistent with the rest of stringr.
